In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("practice_sales.csv")

df.shape

(20, 9)

In [4]:
df.info

<bound method DataFrame.info of     order_id customer_name         product     category  quantity  unit_price  \
0       1001    Priya Nair  Wireless Mouse  Electronics       2.0       15.99
1       1002   Rahul Verma    Office Chair    Furniture       1.0       89.50
2       1003    Sara Ahmed    Notebook Set   Stationery       5.0        3.25
3       1004    Priya Nair     USB-C Cable  Electronics       3.0         NaN
4       1005   John Mathew       Desk Lamp    Furniture       1.0       22.00
5       1006           NaN  Wireless Mouse  Electronics       1.0       15.99
6       1007    Anjali Rao       Bookshelf    Furniture       1.0      120.00
7       1008   Rahul Verma    Notebook Set   Stationery      10.0        3.25
8       1009  Vikram Singh    Office Chair    Furniture       2.0       89.50
9       1010    Sara Ahmed       Desk Lamp    Furniture       NaN       22.00
10      1011   John Mathew     USB-C Cable  Electronics       4.0        9.99
11      1012    Anjali Rao  Wireless Mouse  Electronics       2.0       15.99
12      1013    Priya Nair  Wireless Mouse  Electronics       2.0       15.99
13      1014  Vikram Singh       Bookshelf    Furniture       1.0      120.00
14      1015   Karan Mehta    Notebook Set   Stationery      20.0        3.25
15      1016   Karan Mehta       Desk Lamp          NaN       1.0       22.00
16      1017    Sara Ahmed    Office Chair    Furniture       1.0         NaN
17      1018   Rahul Verma     USB-C Cable  Electronics       2.0        9.99
18      1019    Anjali Rao    Notebook Set   Stationery       NaN        3.25
19      1020   John Mathew       Bookshelf    Furniture       1.0      120.00

    order_date region  is_returned
0   2023-01-05  South        False
1   2023-01-07  North        False
2   2023-01-09   West        False
3   2023-01-10  South         True
4   2023-01-12   East        False
5   2023-01-13  South        False
6   2023-01-15   West        False
7          NaN  North        False
8   2023-01-18   East         True
9   2023-01-19   West        False
10  2023-01-21   East        False
11  2023-01-22   West        False
12  2023-01-05  South        False
13  2023-01-25   East        False
14  2023-01-27  North        False
15  2023-01-28  North        False
16  2023-01-29   West         True
17  2023-01-30  North        False
18  2023-01-31   West        False
19  2023-02-01   East        False  >

In [8]:
df.isnull().sum()

order_id         0
customer_name    1
product          0
category         1
quantity         2
unit_price       2
order_date       1
region           0
is_returned      0
dtype: int64

In [11]:
df.loc[df["category"] == "Electronics"]

,order_id,customer_name,product,category,quantity,unit_price,order_date,region,is_returned
0,1001,Priya Nair,Wireless Mouse,Electronics,2.0,15.99,2023-01-05,South,False
3,1004,Priya Nair,USB-C Cable,Electronics,3.0,NaN,2023-01-10,South,True
5,1006,NaN,Wireless Mouse,Electronics,1.0,15.99,2023-01-13,South,False
10,1011,John Mathew,USB-C Cable,Electronics,4.0,9.99,2023-01-21,East,False
11,1012,Anjali Rao,Wireless Mouse,Electronics,2.0,15.99,2023-01-22,West,False
12,1013,Priya Nair,Wireless Mouse,Electronics,2.0,15.99,2023-01-05,South,False
17,1018,Rahul Verma,USB-C Cable,Electronics,2.0,9.99,2023-01-30,North,False

In [12]:
df.loc[df["quantity"] > 3]

,order_id,customer_name,product,category,quantity,unit_price,order_date,region,is_returned
2,1003,Sara Ahmed,Notebook Set,Stationery,5.0,3.25,2023-01-09,West,False
7,1008,Rahul Verma,Notebook Set,Stationery,10.0,3.25,NaN,North,False
10,1011,John Mathew,USB-C Cable,Electronics,4.0,9.99,2023-01-21,East,False
14,1015,Karan Mehta,Notebook Set,Stationery,20.0,3.25,2023-01-27,North,False

In [9]:
df.loc[(df["region"] == "West") & (df["is_returned"] == True)]

,order_id,customer_name,product,category,quantity,unit_price,order_date,region,is_returned
16,1017,Sara Ahmed,Office Chair,Furniture,1.0,NaN,2023-01-29,West,True

In [17]:
df.loc[df["unit_price"] > 50, "customer_name"]

1      Rahul Verma
6       Anjali Rao
8     Vikram Singh
13    Vikram Singh
19     John Mathew
Name: customer_name, dtype: str

In [20]:
df.loc[df["customer_name"].isna()]

,order_id,customer_name,product,category,quantity,unit_price,order_date,region,is_returned
5,1006,NaN,Wireless Mouse,Electronics,1.0,15.99,2023-01-13,South,False

In [27]:
df["unit_price"].fillna(df["unit_price"].mean())

0      15.990000
1      89.500000
2       3.250000
3      38.996667
4      22.000000
5      15.990000
6     120.000000
7       3.250000
8      89.500000
9      22.000000
10      9.990000
11     15.990000
12     15.990000
13    120.000000
14      3.250000
15     22.000000
16     38.996667
17      9.990000
18      3.250000
19    120.000000
Name: unit_price, dtype: float64

In [40]:
df_clean = df.dropna(subset = ["order_date"])

df_clean.head(20)

,order_id,customer_name,product,category,quantity,unit_price,order_date,region,is_returned
0,1001,Priya Nair,Wireless Mouse,Electronics,2.0,15.99,2023-01-05,South,False
1,1002,Rahul Verma,Office Chair,Furniture,1.0,89.50,2023-01-07,North,False
2,1003,Sara Ahmed,Notebook Set,Stationery,5.0,3.25,2023-01-09,West,False
3,1004,Priya Nair,USB-C Cable,Electronics,3.0,NaN,2023-01-10,South,True
4,1005,John Mathew,Desk Lamp,Furniture,1.0,22.00,2023-01-12,East,False
5,1006,NaN,Wireless Mouse,Electronics,1.0,15.99,2023-01-13,South,False
6,1007,Anjali Rao,Bookshelf,Furniture,1.0,120.00,2023-01-15,West,False
8,1009,Vikram Singh,Office Chair,Furniture,2.0,89.50,2023-01-18,East,True
9,1010,Sara Ahmed,Desk Lamp,Furniture,NaN,22.00,2023-01-19,West,False
10,1011,John Mathew,USB-C Cable,Electronics,4.0,9.99,2023-01-21,East,False
11,1012,Anjali Rao,Wireless Mouse,Electronics,2.0,15.99,2023-01-22,West,False
12,1013,Priya Nair,Wireless Mouse,Electronics,2.0,15.99,2023-01-05,South,False
13,1014,Vikram Singh,Bookshelf,Furniture,1.0,120.00,2023-01-25,East,False
14,1015,Karan Mehta,Notebook Set,Stationery,20.0,3.25,2023-01-27,North,False
15,1016,Karan Mehta,Desk Lamp,NaN,1.0,22.00,2023-01-28,North,False
16,1017,Sara Ahmed,Office Chair,Furniture,1.0,NaN,2023-01-29,West,True
17,1018,Rahul Verma,USB-C Cable,Electronics,2.0,9.99,2023-01-30,North,False
18,1019,Anjali Rao,Notebook Set,Stationery,NaN,3.25,2023-01-31,West,False
19,1020,John Mathew,Bookshelf,Furniture,1.0,120.00,2023-02-01,East,False

In [41]:
df["category"].fillna("Unknown")

0     Electronics
1       Furniture
2      Stationery
3     Electronics
4       Furniture
5     Electronics
6       Furniture
7      Stationery
8       Furniture
9       Furniture
10    Electronics
11    Electronics
12    Electronics
13      Furniture
14     Stationery
15        Unknown
16      Furniture
17    Electronics
18     Stationery
19      Furniture
Name: category, dtype: str

In [47]:
df.rename(columns = {"unit_price" : "price",
                    "order_date" : "date"})

,order_id,customer_name,product,category,quantity,price,date,region,is_returned
0,1001,Priya Nair,Wireless Mouse,Electronics,2.0,15.99,2023-01-05,South,False
1,1002,Rahul Verma,Office Chair,Furniture,1.0,89.50,2023-01-07,North,False
2,1003,Sara Ahmed,Notebook Set,Stationery,5.0,3.25,2023-01-09,West,False
3,1004,Priya Nair,USB-C Cable,Electronics,3.0,NaN,2023-01-10,South,True
4,1005,John Mathew,Desk Lamp,Furniture,1.0,22.00,2023-01-12,East,False
5,1006,NaN,Wireless Mouse,Electronics,1.0,15.99,2023-01-13,South,False
6,1007,Anjali Rao,Bookshelf,Furniture,1.0,120.00,2023-01-15,West,False
7,1008,Rahul Verma,Notebook Set,Stationery,10.0,3.25,NaN,North,False
8,1009,Vikram Singh,Office Chair,Furniture,2.0,89.50,2023-01-18,East,True
9,1010,Sara Ahmed,Desk Lamp,Furniture,NaN,22.00,2023-01-19,West,False
10,1011,John Mathew,USB-C Cable,Electronics,4.0,9.99,2023-01-21,East,False
11,1012,Anjali Rao,Wireless Mouse,Electronics,2.0,15.99,2023-01-22,West,False
12,1013,Priya Nair,Wireless Mouse,Electronics,2.0,15.99,2023-01-05,South,False
13,1014,Vikram Singh,Bookshelf,Furniture,1.0,120.00,2023-01-25,East,False
14,1015,Karan Mehta,Notebook Set,Stationery,20.0,3.25,2023-01-27,North,False
15,1016,Karan Mehta,Desk Lamp,NaN,1.0,22.00,2023-01-28,North,False
16,1017,Sara Ahmed,Office Chair,Furniture,1.0,NaN,2023-01-29,West,True
17,1018,Rahul Verma,USB-C Cable,Electronics,2.0,9.99,2023-01-30,North,False
18,1019,Anjali Rao,Notebook Set,Stationery,NaN,3.25,2023-01-31,West,False
19,1020,John Mathew,Bookshelf,Furniture,1.0,120.00,2023-02-01,East,False

In [48]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
dtype: bool

In [56]:
df.index

RangeIndex(start=0, stop=20, step=1)

In [67]:
df["total_price"] = df["quantity"] * df["unit_price"]

df.groupby("region")["total_price"].sum()

region
East     480.96
North    228.98
South     79.95
West     168.23
Name: total_price, dtype: float64

In [66]:
df["customer_name"].value_counts().idxmax()

'Priya Nair'

In [74]:
df[["customer_name", "product"]]

   customer_name         product
0     Priya Nair  Wireless Mouse
1    Rahul Verma    Office Chair
2     Sara Ahmed    Notebook Set
3     Priya Nair     USB-C Cable
4    John Mathew       Desk Lamp
5            NaN  Wireless Mouse
6     Anjali Rao       Bookshelf
7    Rahul Verma    Notebook Set
8   Vikram Singh    Office Chair
9     Sara Ahmed       Desk Lamp
10   John Mathew     USB-C Cable
11    Anjali Rao  Wireless Mouse
12    Priya Nair  Wireless Mouse
13  Vikram Singh       Bookshelf
14   Karan Mehta    Notebook Set
15   Karan Mehta       Desk Lamp
16    Sara Ahmed    Office Chair
17   Rahul Verma     USB-C Cable
18    Anjali Rao    Notebook Set
19   John Mathew       Bookshelf

In [75]:
df.loc[df["category"] == "Furniture"]

,order_id,customer_name,product,category,quantity,unit_price,order_date,region,is_returned,total_price
1,1002,Rahul Verma,Office Chair,Furniture,1.0,89.5,2023-01-07,North,False,89.5
4,1005,John Mathew,Desk Lamp,Furniture,1.0,22.0,2023-01-12,East,False,22.0
6,1007,Anjali Rao,Bookshelf,Furniture,1.0,120.0,2023-01-15,West,False,120.0
8,1009,Vikram Singh,Office Chair,Furniture,2.0,89.5,2023-01-18,East,True,179.0
9,1010,Sara Ahmed,Desk Lamp,Furniture,NaN,22.0,2023-01-19,West,False,NaN
13,1014,Vikram Singh,Bookshelf,Furniture,1.0,120.0,2023-01-25,East,False,120.0
16,1017,Sara Ahmed,Office Chair,Furniture,1.0,NaN,2023-01-29,West,True,NaN
19,1020,John Mathew,Bookshelf,Furniture,1.0,120.0,2023-02-01,East,False,120.0

In [76]:
df.loc[df["is_returned"] == True]

,order_id,customer_name,product,category,quantity,unit_price,order_date,region,is_returned,total_price
3,1004,Priya Nair,USB-C Cable,Electronics,3.0,NaN,2023-01-10,South,True,NaN
8,1009,Vikram Singh,Office Chair,Furniture,2.0,89.5,2023-01-18,East,True,179.0
16,1017,Sara Ahmed,Office Chair,Furniture,1.0,NaN,2023-01-29,West,True,NaN

In [78]:
df.info

<bound method DataFrame.info of     order_id customer_name         product     category  quantity  unit_price  \
0       1001    Priya Nair  Wireless Mouse  Electronics       2.0       15.99
1       1002   Rahul Verma    Office Chair    Furniture       1.0       89.50
2       1003    Sara Ahmed    Notebook Set   Stationery       5.0        3.25
3       1004    Priya Nair     USB-C Cable  Electronics       3.0         NaN
4       1005   John Mathew       Desk Lamp    Furniture       1.0       22.00
5       1006           NaN  Wireless Mouse  Electronics       1.0       15.99
6       1007    Anjali Rao       Bookshelf    Furniture       1.0      120.00
7       1008   Rahul Verma    Notebook Set   Stationery      10.0        3.25
8       1009  Vikram Singh    Office Chair    Furniture       2.0       89.50
9       1010    Sara Ahmed       Desk Lamp    Furniture       NaN       22.00
10      1011   John Mathew     USB-C Cable  Electronics       4.0        9.99
11      1012    Anjali Rao  Wireless Mouse  Electronics       2.0       15.99
12      1013    Priya Nair  Wireless Mouse  Electronics       2.0       15.99
13      1014  Vikram Singh       Bookshelf    Furniture       1.0      120.00
14      1015   Karan Mehta    Notebook Set   Stationery      20.0        3.25
15      1016   Karan Mehta       Desk Lamp          NaN       1.0       22.00
16      1017    Sara Ahmed    Office Chair    Furniture       1.0         NaN
17      1018   Rahul Verma     USB-C Cable  Electronics       2.0        9.99
18      1019    Anjali Rao    Notebook Set   Stationery       NaN        3.25
19      1020   John Mathew       Bookshelf    Furniture       1.0      120.00

    order_date region  is_returned  total_price
0   2023-01-05  South        False        31.98
1   2023-01-07  North        False        89.50
2   2023-01-09   West        False        16.25
3   2023-01-10  South         True          NaN
4   2023-01-12   East        False        22.00
5   2023-01-13  South        False        15.99
6   2023-01-15   West        False       120.00
7          NaN  North        False        32.50
8   2023-01-18   East         True       179.00
9   2023-01-19   West        False          NaN
10  2023-01-21   East        False        39.96
11  2023-01-22   West        False        31.98
12  2023-01-05  South        False        31.98
13  2023-01-25   East        False       120.00
14  2023-01-27  North        False        65.00
15  2023-01-28  North        False        22.00
16  2023-01-29   West         True          NaN
17  2023-01-30  North        False        19.98
18  2023-01-31   West        False          NaN
19  2023-02-01   East        False       120.00  >

In [81]:
df.loc[df["region"] == "South", ["region", "product"]]

   region         product
0   South  Wireless Mouse
3   South     USB-C Cable
5   South  Wireless Mouse
12  South  Wireless Mouse

In [82]:
df.isnull().sum()

order_id         0
customer_name    1
product          0
category         1
quantity         2
unit_price       2
order_date       1
region           0
is_returned      0
total_price      4
dtype: int64

In [85]:
df.loc[df["unit_price"].isna()]

,order_id,customer_name,product,category,quantity,unit_price,order_date,region,is_returned,total_price
3,1004,Priya Nair,USB-C Cable,Electronics,3.0,NaN,2023-01-10,South,True,NaN
16,1017,Sara Ahmed,Office Chair,Furniture,1.0,NaN,2023-01-29,West,True,NaN

In [5]:
df.rename(columns = {"unit_price" : "price"})

,order_id,customer_name,product,category,quantity,price,order_date,region,is_returned
0,1001,Priya Nair,Wireless Mouse,Electronics,2.0,15.99,2023-01-05,South,False
1,1002,Rahul Verma,Office Chair,Furniture,1.0,89.50,2023-01-07,North,False
2,1003,Sara Ahmed,Notebook Set,Stationery,5.0,3.25,2023-01-09,West,False
3,1004,Priya Nair,USB-C Cable,Electronics,3.0,NaN,2023-01-10,South,True
4,1005,John Mathew,Desk Lamp,Furniture,1.0,22.00,2023-01-12,East,False
5,1006,NaN,Wireless Mouse,Electronics,1.0,15.99,2023-01-13,South,False
6,1007,Anjali Rao,Bookshelf,Furniture,1.0,120.00,2023-01-15,West,False
7,1008,Rahul Verma,Notebook Set,Stationery,10.0,3.25,NaN,North,False
8,1009,Vikram Singh,Office Chair,Furniture,2.0,89.50,2023-01-18,East,True
9,1010,Sara Ahmed,Desk Lamp,Furniture,NaN,22.00,2023-01-19,West,False
10,1011,John Mathew,USB-C Cable,Electronics,4.0,9.99,2023-01-21,East,False
11,1012,Anjali Rao,Wireless Mouse,Electronics,2.0,15.99,2023-01-22,West,False
12,1013,Priya Nair,Wireless Mouse,Electronics,2.0,15.99,2023-01-05,South,False
13,1014,Vikram Singh,Bookshelf,Furniture,1.0,120.00,2023-01-25,East,False
14,1015,Karan Mehta,Notebook Set,Stationery,20.0,3.25,2023-01-27,North,False
15,1016,Karan Mehta,Desk Lamp,NaN,1.0,22.00,2023-01-28,North,False
16,1017,Sara Ahmed,Office Chair,Furniture,1.0,NaN,2023-01-29,West,True
17,1018,Rahul Verma,USB-C Cable,Electronics,2.0,9.99,2023-01-30,North,False
18,1019,Anjali Rao,Notebook Set,Stationery,NaN,3.25,2023-01-31,West,False
19,1020,John Mathew,Bookshelf,Furniture,1.0,120.00,2023-02-01,East,False

In [9]:
df["region"].value_counts()

region
West     6
North    5
East     5
South    4
Name: count, dtype: int64

In [10]:
df["product"].value_counts()

product
Wireless Mouse    4
Notebook Set      4
Office Chair      3
USB-C Cable       3
Desk Lamp         3
Bookshelf         3
Name: count, dtype: int64