In [4]:
import pandas as pd

In [5]:
ages =  pd.Series([18, 27, 41, 19])

print(ages)

0    18
1    27
2    41
3    19
dtype: int64

In [6]:
df = pd.DataFrame({
    "names" : ["Shibil", "Rahul", "Rajan", "Arjun"],
    "ages" : [18, 27, 41, 19]})

df.head()

    names  ages
0  Shibil    18
1   Rahul    27
2   Rajan    41
3   Arjun    19

In [7]:
ds = pd.read_csv("practice_employees.csv")

ds.head()

,employee_id,name,age,department,city,salary,joined_at,is_manager
0,101,Alice Johnson,25.0,Engineering,NYC,85000.0,2021-03-15,False
1,102,Bob Smith,32.0,Sales,LA,62000.0,2019-07-01,True
2,103,Charlie Lee,45.0,Engineering,NYC,95000.0,2015-11-23,True
3,104,Dana White,29.0,Marketing,SF,58000.0,2020-01-10,False
4,105,Ethan Brown,NaN,Sales,LA,NaN,2022-06-05,False

In [8]:
ds.tail()

,employee_id,name,age,department,city,salary,joined_at,is_manager
10,111,Alice Johnson,25.0,Engineering,NYC,85000.0,2021-03-15,False
11,112,Kevin Young,52.0,HR,NYC,72000.0,2010-05-05,True
12,113,Laura Hill,24.0,Marketing,LA,50000.0,2023-01-17,False
13,114,Mike Davis,36.0,Sales,SF,64000.0,2017-10-11,False
14,115,Nina Patel,31.0,Engineering,NYC,89000.0,2020-03-03,False

In [9]:
ds.sample()

,employee_id,name,age,department,city,salary,joined_at,is_manager
9,110,Julia Adams,NaN,HR,SF,54000.0,2021-08-22,False

In [10]:
ds.info()

<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   employee_id  15 non-null     int64
 1   name         15 non-null     str
 2   age          13 non-null     float64
 3   department   15 non-null     str
 4   city         14 non-null     str
 5   salary       13 non-null     float64
 6   joined_at    15 non-null     str
 7   is_manager   15 non-null     bool
dtypes: bool(1), float64(2), int64(1), str(4)
memory usage: 987.0 bytes

In [11]:
ds.describe()

       employee_id        age        salary
count    15.000000  13.000000     13.000000
mean    108.000000  33.692308  73846.153846
std       4.472136   8.479236  15603.664921
min     101.000000  24.000000  50000.000000
25%     104.500000  27.000000  62000.000000
50%     108.000000  32.000000  72000.000000
75%     111.500000  38.000000  88000.000000
max     115.000000  52.000000  95000.000000

In [12]:
ds.shape

(15, 8)

In [13]:
ds.size

120

In [14]:
ds.columns

Index(['employee_id', 'name', 'age', 'department', 'city', 'salary',
       'joined_at', 'is_manager'],
      dtype='str')

In [15]:
ds.index

RangeIndex(start=0, stop=15, step=1)

In [16]:
ds.dtypes

employee_id      int64
name               str
age            float64
department         str
city               str
salary         float64
joined_at          str
is_manager        bool
dtype: object

In [17]:
ds[["name", "age"]]

             name   age
0   Alice Johnson  25.0
1       Bob Smith  32.0
2     Charlie Lee  45.0
3      Dana White  29.0
4     Ethan Brown   NaN
5     Fiona Green  38.0
6     George King  41.0
7    Hannah Scott  27.0
8      Ian Wright  33.0
9     Julia Adams   NaN
10  Alice Johnson  25.0
11    Kevin Young  52.0
12     Laura Hill  24.0
13     Mike Davis  36.0
14     Nina Patel  31.0

In [18]:
ds["name"]

0     Alice Johnson
1         Bob Smith
2       Charlie Lee
3        Dana White
4       Ethan Brown
5       Fiona Green
6       George King
7      Hannah Scott
8        Ian Wright
9       Julia Adams
10    Alice Johnson
11      Kevin Young
12       Laura Hill
13       Mike Davis
14       Nina Patel
Name: name, dtype: str

In [19]:
ds.loc[0]

employee_id              101
name           Alice Johnson
age                     25.0
department       Engineering
city                     NYC
salary               85000.0
joined_at         2021-03-15
is_manager             False
Name: 0, dtype: object

In [20]:
ds.loc[0:2, ["name", "age"]]

            name   age
0  Alice Johnson  25.0
1      Bob Smith  32.0
2    Charlie Lee  45.0

In [21]:
ds.iloc[0:2]

,employee_id,name,age,department,city,salary,joined_at,is_manager
0,101,Alice Johnson,25.0,Engineering,NYC,85000.0,2021-03-15,False
1,102,Bob Smith,32.0,Sales,LA,62000.0,2019-07-01,True

In [22]:
ds[ds["department"] == "Sales"]

,employee_id,name,age,department,city,salary,joined_at,is_manager
1,102,Bob Smith,32.0,Sales,LA,62000.0,2019-07-01,True
4,105,Ethan Brown,NaN,Sales,LA,NaN,2022-06-05,False
7,108,Hannah Scott,27.0,Sales,NYC,NaN,2023-04-01,False
13,114,Mike Davis,36.0,Sales,SF,64000.0,2017-10-11,False

In [23]:
ds.isnull()

,employee_id,name,age,department,city,salary,joined_at,is_manager
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,True,False,False,True,False,False
5,False,False,False,False,True,False,False,False
6,False,False,False,False,False,False,False,False
7,False,False,False,False,False,True,False,False
8,False,False,False,False,False,False,False,False
9,False,False,True,False,False,False,False,False
10,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False

In [24]:
ds.notnull()

    employee_id  name    age  department   city  salary  joined_at  is_manager
0          True  True   True        True   True    True       True        True
1          True  True   True        True   True    True       True        True
2          True  True   True        True   True    True       True        True
3          True  True   True        True   True    True       True        True
4          True  True  False        True   True   False       True        True
5          True  True   True        True  False    True       True        True
6          True  True   True        True   True    True       True        True
7          True  True   True        True   True   False       True        True
8          True  True   True        True   True    True       True        True
9          True  True  False        True   True    True       True        True
10         True  True   True        True   True    True       True        True
11         True  True   True        True   True    True       True        True
12         True  True   True        True   True    True       True        True
13         True  True   True        True   True    True       True        True
14         True  True   True        True   True    True       True        True

In [25]:
#fill in missing values

ds["age"].fillna(100)

0      25.0
1      32.0
2      45.0
3      29.0
4     100.0
5      38.0
6      41.0
7      27.0
8      33.0
9     100.0
10     25.0
11     52.0
12     24.0
13     36.0
14     31.0
Name: age, dtype: float64

In [26]:
ds.drop(1)

,employee_id,name,age,department,city,salary,joined_at,is_manager
0,101,Alice Johnson,25.0,Engineering,NYC,85000.0,2021-03-15,False
2,103,Charlie Lee,45.0,Engineering,NYC,95000.0,2015-11-23,True
3,104,Dana White,29.0,Marketing,SF,58000.0,2020-01-10,False
4,105,Ethan Brown,NaN,Sales,LA,NaN,2022-06-05,False
5,106,Fiona Green,38.0,Engineering,NaN,91000.0,2018-09-30,False
6,107,George King,41.0,Marketing,SF,67000.0,2016-02-14,True
7,108,Hannah Scott,27.0,Sales,NYC,NaN,2023-04-01,False
8,109,Ian Wright,33.0,Engineering,LA,88000.0,2019-12-19,False
9,110,Julia Adams,NaN,HR,SF,54000.0,2021-08-22,False
10,111,Alice Johnson,25.0,Engineering,NYC,85000.0,2021-03-15,False
11,112,Kevin Young,52.0,HR,NYC,72000.0,2010-05-05,True
12,113,Laura Hill,24.0,Marketing,LA,50000.0,2023-01-17,False
13,114,Mike Davis,36.0,Sales,SF,64000.0,2017-10-11,False
14,115,Nina Patel,31.0,Engineering,NYC,89000.0,2020-03-03,False

In [27]:
ds.drop_duplicates()

,employee_id,name,age,department,city,salary,joined_at,is_manager
0,101,Alice Johnson,25.0,Engineering,NYC,85000.0,2021-03-15,False
1,102,Bob Smith,32.0,Sales,LA,62000.0,2019-07-01,True
2,103,Charlie Lee,45.0,Engineering,NYC,95000.0,2015-11-23,True
3,104,Dana White,29.0,Marketing,SF,58000.0,2020-01-10,False
4,105,Ethan Brown,NaN,Sales,LA,NaN,2022-06-05,False
5,106,Fiona Green,38.0,Engineering,NaN,91000.0,2018-09-30,False
6,107,George King,41.0,Marketing,SF,67000.0,2016-02-14,True
7,108,Hannah Scott,27.0,Sales,NYC,NaN,2023-04-01,False
8,109,Ian Wright,33.0,Engineering,LA,88000.0,2019-12-19,False
9,110,Julia Adams,NaN,HR,SF,54000.0,2021-08-22,False
10,111,Alice Johnson,25.0,Engineering,NYC,85000.0,2021-03-15,False
11,112,Kevin Young,52.0,HR,NYC,72000.0,2010-05-05,True
12,113,Laura Hill,24.0,Marketing,LA,50000.0,2023-01-17,False
13,114,Mike Davis,36.0,Sales,SF,64000.0,2017-10-11,False
14,115,Nina Patel,31.0,Engineering,NYC,89000.0,2020-03-03,False

In [28]:
ds.replace("Bob Smith", "id")

,employee_id,name,age,department,city,salary,joined_at,is_manager
0,101,Alice Johnson,25.0,Engineering,NYC,85000.0,2021-03-15,False
1,102,id,32.0,Sales,LA,62000.0,2019-07-01,True
2,103,Charlie Lee,45.0,Engineering,NYC,95000.0,2015-11-23,True
3,104,Dana White,29.0,Marketing,SF,58000.0,2020-01-10,False
4,105,Ethan Brown,NaN,Sales,LA,NaN,2022-06-05,False
5,106,Fiona Green,38.0,Engineering,NaN,91000.0,2018-09-30,False
6,107,George King,41.0,Marketing,SF,67000.0,2016-02-14,True
7,108,Hannah Scott,27.0,Sales,NYC,NaN,2023-04-01,False
8,109,Ian Wright,33.0,Engineering,LA,88000.0,2019-12-19,False
9,110,Julia Adams,NaN,HR,SF,54000.0,2021-08-22,False
10,111,Alice Johnson,25.0,Engineering,NYC,85000.0,2021-03-15,False
11,112,Kevin Young,52.0,HR,NYC,72000.0,2010-05-05,True
12,113,Laura Hill,24.0,Marketing,LA,50000.0,2023-01-17,False
13,114,Mike Davis,36.0,Sales,SF,64000.0,2017-10-11,False
14,115,Nina Patel,31.0,Engineering,NYC,89000.0,2020-03-03,False

In [29]:
ds.rename(columns = {"employee_id":"id"})

,id,name,age,department,city,salary,joined_at,is_manager
0,101,Alice Johnson,25.0,Engineering,NYC,85000.0,2021-03-15,False
1,102,Bob Smith,32.0,Sales,LA,62000.0,2019-07-01,True
2,103,Charlie Lee,45.0,Engineering,NYC,95000.0,2015-11-23,True
3,104,Dana White,29.0,Marketing,SF,58000.0,2020-01-10,False
4,105,Ethan Brown,NaN,Sales,LA,NaN,2022-06-05,False
5,106,Fiona Green,38.0,Engineering,NaN,91000.0,2018-09-30,False
6,107,George King,41.0,Marketing,SF,67000.0,2016-02-14,True
7,108,Hannah Scott,27.0,Sales,NYC,NaN,2023-04-01,False
8,109,Ian Wright,33.0,Engineering,LA,88000.0,2019-12-19,False
9,110,Julia Adams,NaN,HR,SF,54000.0,2021-08-22,False
10,111,Alice Johnson,25.0,Engineering,NYC,85000.0,2021-03-15,False
11,112,Kevin Young,52.0,HR,NYC,72000.0,2010-05-05,True
12,113,Laura Hill,24.0,Marketing,LA,50000.0,2023-01-17,False
13,114,Mike Davis,36.0,Sales,SF,64000.0,2017-10-11,False
14,115,Nina Patel,31.0,Engineering,NYC,89000.0,2020-03-03,False

In [30]:
ds.iloc[0,2]

np.float64(25.0)

In [31]:
ds["Passed"] = True

ds["Bonus"] = (ds["salary"]*0.10)

ds.head(15)

,employee_id,name,age,department,city,salary,joined_at,is_manager,Passed,Bonus
0,101,Alice Johnson,25.0,Engineering,NYC,85000.0,2021-03-15,False,True,8500.0
1,102,Bob Smith,32.0,Sales,LA,62000.0,2019-07-01,True,True,6200.0
2,103,Charlie Lee,45.0,Engineering,NYC,95000.0,2015-11-23,True,True,9500.0
3,104,Dana White,29.0,Marketing,SF,58000.0,2020-01-10,False,True,5800.0
4,105,Ethan Brown,NaN,Sales,LA,NaN,2022-06-05,False,True,NaN
5,106,Fiona Green,38.0,Engineering,NaN,91000.0,2018-09-30,False,True,9100.0
6,107,George King,41.0,Marketing,SF,67000.0,2016-02-14,True,True,6700.0
7,108,Hannah Scott,27.0,Sales,NYC,NaN,2023-04-01,False,True,NaN
8,109,Ian Wright,33.0,Engineering,LA,88000.0,2019-12-19,False,True,8800.0
9,110,Julia Adams,NaN,HR,SF,54000.0,2021-08-22,False,True,5400.0
10,111,Alice Johnson,25.0,Engineering,NYC,85000.0,2021-03-15,False,True,8500.0
11,112,Kevin Young,52.0,HR,NYC,72000.0,2010-05-05,True,True,7200.0
12,113,Laura Hill,24.0,Marketing,LA,50000.0,2023-01-17,False,True,5000.0
13,114,Mike Davis,36.0,Sales,SF,64000.0,2017-10-11,False,True,6400.0
14,115,Nina Patel,31.0,Engineering,NYC,89000.0,2020-03-03,False,True,8900.0

In [32]:
ds.isnull().sum()

employee_id    0
name           0
age            2
department     0
city           1
salary         2
joined_at      0
is_manager     0
Passed         0
Bonus          2
dtype: int64

In [33]:
ds["age"].fillna(ds["age"].mean())

0     25.000000
1     32.000000
2     45.000000
3     29.000000
4     33.692308
5     38.000000
6     41.000000
7     27.000000
8     33.000000
9     33.692308
10    25.000000
11    52.000000
12    24.000000
13    36.000000
14    31.000000
Name: age, dtype: float64

In [34]:
ds.sort_values("age")

,employee_id,name,age,department,city,salary,joined_at,is_manager,Passed,Bonus
12,113,Laura Hill,24.0,Marketing,LA,50000.0,2023-01-17,False,True,5000.0
0,101,Alice Johnson,25.0,Engineering,NYC,85000.0,2021-03-15,False,True,8500.0
10,111,Alice Johnson,25.0,Engineering,NYC,85000.0,2021-03-15,False,True,8500.0
7,108,Hannah Scott,27.0,Sales,NYC,NaN,2023-04-01,False,True,NaN
3,104,Dana White,29.0,Marketing,SF,58000.0,2020-01-10,False,True,5800.0
14,115,Nina Patel,31.0,Engineering,NYC,89000.0,2020-03-03,False,True,8900.0
1,102,Bob Smith,32.0,Sales,LA,62000.0,2019-07-01,True,True,6200.0
8,109,Ian Wright,33.0,Engineering,LA,88000.0,2019-12-19,False,True,8800.0
13,114,Mike Davis,36.0,Sales,SF,64000.0,2017-10-11,False,True,6400.0
5,106,Fiona Green,38.0,Engineering,NaN,91000.0,2018-09-30,False,True,9100.0
6,107,George King,41.0,Marketing,SF,67000.0,2016-02-14,True,True,6700.0
2,103,Charlie Lee,45.0,Engineering,NYC,95000.0,2015-11-23,True,True,9500.0
11,112,Kevin Young,52.0,HR,NYC,72000.0,2010-05-05,True,True,7200.0
4,105,Ethan Brown,NaN,Sales,LA,NaN,2022-06-05,False,True,NaN
9,110,Julia Adams,NaN,HR,SF,54000.0,2021-08-22,False,True,5400.0

In [35]:
ds.groupby("city")["salary"].mean()

city
LA     66666.666667
NYC    85200.000000
SF     60750.000000
Name: salary, dtype: float64

In [36]:
data1 = {
    "id" : [1, 2, 3],
    "age" : [19, 32, 24]
       }

data2 = {
    "id" : [1, 2, 3],
    "roll_no" : [19, 32, 24]
        }

df1 = pd.DataFrame(data1)

df2 = pd.DataFrame(data2)

pd.merge(
    df1, df2, on="id"
)

   id  age  roll_no
0   1   19       19
1   2   32       32
2   3   24       24

In [37]:
data1 = {
    "id" : [1, 2, 3],
    "age" : [19, 32, 24]
       }

data2 = {
    "id" : [1, 2, 3],
    "roll_no" : [19, 32, 24]
        }

pd.concat([df1, df2])

   id   age  roll_no
0   1  19.0      NaN
1   2  32.0      NaN
2   3  24.0      NaN
0   1   NaN     19.0
1   2   NaN     32.0
2   3   NaN     24.0

In [38]:
ds.to_csv("output_1.csv", index=False)

In [39]:
ages = pd.Series(
    ["Rahul","Anu","John"],
    [18,20,22],
)

print(ages)

18    Rahul
20      Anu
22     John
dtype: str

In [40]:
ages = pd.Series(
    ["Rahul","Anu","John"],
    [18,20,22],
)

print(ages)

18    Rahul
20      Anu
22     John
dtype: str

In [41]:
ages = pd.Series(
    ["Rahul","Anu","John"],
    [18,20,22],
)

print(ages)

18    Rahul
20      Anu
22     John
dtype: str

In [42]:
ages = pd.Series(
    ["Rahul","Anu","John"],
    [18,20,22],
)

print(ages)

18    Rahul
20      Anu
22     John
dtype: str

In [43]:
ages = pd.Series(
    ["Rahul","Anu","John"],
    [18,20,22],
)

print(ages)

18    Rahul
20      Anu
22     John
dtype: str

In [44]:
ages = pd.Series(
    ["Rahul","Anu","John"],
    [18,20,22],
)

print(ages)

18    Rahul
20      Anu
22     John
dtype: str

In [45]:
ages = pd.Series(
    ["Rahul","Anu","John"],
    [18,20,22],
) 

print(ages)

18    Rahul
20      Anu
22     John
dtype: str

In [46]:
ds.groupby("department")["salary"].agg(["mean", "max"])

                     mean      max
department
Engineering  88833.333333  95000.0
HR           63000.000000  72000.0
Marketing    58333.333333  67000.0
Sales        63000.000000  64000.0

In [47]:
ds.iloc[0]

employee_id              101
name           Alice Johnson
age                     25.0
department       Engineering
city                     NYC
salary               85000.0
joined_at         2021-03-15
is_manager             False
Passed                  True
Bonus                 8500.0
Name: 0, dtype: object

In [50]:
df1 = pd.DataFrame({'Name': ['Alice', 'Bob'], 'Age': [25, 30]})
df2 = pd.DataFrame({'City': ['New York', 'Los Angeles'], 'Salary': [70000, 80000]})

# Stack horizontally
result = pd.concat([df1, df2], axis=1)
print(result)

    Name  Age         City  Salary
0  Alice   25     New York   70000
1    Bob   30  Los Angeles   80000

In [57]:
import pandas as pd

df1 = pd.DataFrame({'Name': ['Alice', 'Bob'], 'Age': [25, 30]})
df2 = pd.DataFrame({'Name': ['Charlie', 'David'], 'Age': [35, 40]})

# Stack vertically
result = pd.concat([df1, df2])
print(result)

      Name  Age
0    Alice   25
1      Bob   30
0  Charlie   35
1    David   40

In [62]:
df1 = pd.DataFrame({
    "Name": ["Alice", "Bob"]
})

df2 = pd.DataFrame({
    "Marks": [90, 85]
})

result = pd.concat([df1, df2], axis=1)

print(result)

    Name  Marks
0  Alice     90
1    Bob     85

In [63]:
print("Hello World!")

Hello World!